spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
    url: jdbc:mysql://localhost:3306/voice


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true



jwt:
  secret:
    key: ${jwt_secret_key}

